### ISSUE TITLE
Segmentation fault (core dumped) related to spconv

### ISSUE THREAD

**Issue by enesdorukadastec** [darrenjkt/MS3D#12]
Hi I followed the installation instructions, but I got segmentation error after "python -m pcdet.datasets.nuscenes.nuscenes_dataset  --func create_nuscenes_infos  --cfg_file tools/cfgs/dataset_configs/nuscenes_dataset.yaml". CUDA version is correct, I checked whether Cuda version is available or not using Pytorch and I got True. 

ccimport                  0.3.7                    pypi_0    pypi
certifi                   2023.7.22                pypi_0    pypi
charset-normalizer        3.3.0                    pypi_0    pypi
cumm-cu111                0.2.9                    pypi_0    pypi
easydict                  1.10                     pypi_0    pypi
fire                      0.5.0                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.31.5                   pypi_0    pypi
importlib-metadata        6.8.0                    pypi_0    pypi
lark                      1.1.7                    pypi_0    pypi
lazy-loader               0.3                      pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
llvmlite                  0.41.0                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  3.1                      pypi_0    pypi
ninja                     1.11.1                   pypi_0    pypi
numba                     0.58.0                   pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
openssl                   3.0.11               h7f8727e_2  
packaging                 23.2                     pypi_0    pypi
pccm                      0.3.4                    pypi_0    pypi
pcdet                     0.6.0+df3d0fa             dev_0    <develop>
pillow                    10.0.1                   pypi_0    pypi
pip                       23.2.1           py38h06a4308_0  
portalocker               2.8.2                    pypi_0    pypi
protobuf                  4.24.3                   pypi_0    pypi
pybind11                  2.11.1                   pypi_0    pypi
python                    3.8.18               h955ad1f_0  
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.31.0                   pypi_0    pypi
scikit-image              0.21.0                   pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                68.0.0           py38h06a4308_0  
sharedarray               3.2.3                    pypi_0    pypi
spconv-cu111              2.1.25                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
tensorboardx              2.6.2.2                  pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
tifffile                  2023.7.10                pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
torch                     1.8.1+cu111              pypi_0    pypi
torch-scatter             2.1.1                    pypi_0    pypi
torchaudio                0.8.1                    pypi_0    pypi
torchvision               0.9.1+cu111              pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
urllib3                   2.0.6                    pypi_0    pypi
wheel                     0.41.2           py38h06a4308_0  
xz                        5.4.2                h5eee18b_0  
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0

**Comment by enesdorukadastec** [comment]
I checked with the print function;  before the error, the processor did not enter the create function.

**Comment by darrenjkt** [comment]
Are you using the docker image we provided? That's the easiest way to directly use our repo.

**Comment by enesdorukadastec** [comment]
> Are you using the docker image we provided? That's the easiest way to directly use our repo.

No, i am not,

**Comment by darrenjkt** [comment]
It could be related to this issue: https://github.com/open-mmlab/OpenPCDet/issues/1367

If this doesn't work, maybe you could search the OpenPCDet issues for more potential solutions since this issue is OpenPCDet related. We highly recommend just using our provided docker image cause it should just work out-of-the-box.

**Comment by enesdorukadastec** [comment]
thank @darrenjkt, I will try the docker image.
