### ISSUE TITLE
"round" folders explanation

### ISSUE THREAD

**Issue by enesdorukadastec** [darrenjkt/MS3D#13]
Hi, There are different round folders cfgs/target_dataset but I could not find any information about differences among round folders and explanations. Can you give me information about them?

**Comment by darrenjkt** [comment]
Read the multi-stage self training section in our paper. Or in the MS3D++ presentation, we have a slide where we talk about Iterative Label Refinement. 

The main idea is to do multiple rounds of label generation for the same dataset using the re-trained models from the previous auto-labelled training round.
