### ISSUE TITLE
Auto label with raw data

### ISSUE THREAD

**Issue by enesdoruk** [darrenjkt/MS3D#15]
Hi, I have a bag that includes lidar data and related info. I want to label with the auto-label tool. I think I should create nuscenes format (example dataset) from raw bag data without labels and label with the auto label tool, is it right?

**Comment by darrenjkt** [comment]
What we did for processing our rosbags is to divide up the bag into 20s sequences, then export each frame of the sequence into pcd files. You can do longer than 20s sequences if you wish.

The file structure and auto-labelling instructions can be found in our [custom dataset readme](https://github.com/darrenjkt/MS3D/blob/main/docs/CUSTOM_DATASET_TUTORIAL.md).

Let me know if you have any other questions!

**Comment by enesdorukadastec** [comment]
> What we did for processing our rosbags is to divide up the bag into 20s sequences, then export each frame of the sequence into pcd files. You can do longer than 20s sequences if you wish.
> 
> The file format/structure and auto-labelling instructions can be found in our [custom dataset readme](https://github.com/darrenjkt/MS3D/blob/main/docs/CUSTOM_DATASET_TUTORIAL.md).
> 
> Let me know if you have any other questions!

Thanks for quick answer, i will try

**Comment by darrenjkt** [comment]
We used the C++ PCL function, `pcl::io::savePCDFileASCII`, for exporting each frame of our rosbag to pcd. This should make it directly readable by open3d (which is how we load point cloud files in our custom dataset template).

**Comment by enesdorukadastec** [comment]
Hi @darrenjkt, 

I try to label raw bag data with custom_dataset instructions. I did but i got different result according to the other dataset. 

2023-10-18 11:52:19,683   INFO  recall_roi_0.3: 0.000000
2023-10-18 11:52:19,683   INFO  recall_rcnn_0.3: 0.000000
2023-10-18 11:52:19,684   INFO  recall_roi_0.5: 0.000000
2023-10-18 11:52:19,684   INFO  recall_rcnn_0.5: 0.000000
2023-10-18 11:52:19,684   INFO  recall_roi_0.7: 0.000000
2023-10-18 11:52:19,684   INFO  recall_rcnn_0.7: 0.000000
2023-10-18 11:52:19,684   INFO  Average predicted number of objects(399 samples): 30.757

I have no annotation info. is this result related to label information?

**Comment by enesdorukadastec** [comment]
Hi @darrenjkt again, 

I use custom_dataset_da.yaml but i got error about kitti eval 

ile "../pcdet/datasets/kitti/kitti_object_eval_python/eval.py", line 661, in get_official_eval_result
    current_classes_int.append(name_to_class[curcls])
KeyError: 'Vehicle'

I use default yaml config 

CLASS_NAMES: ['Vehicle', 'Pedestrian', 'Cyclist']
CLASS_MAPPING: {'car': 'Vehicle',
                'truck': 'Vehicle',
                'bus': 'Vehicle',
                'Vehicle': 'Vehicle',
                'motorcycle': 'Cyclist',
                'bicycle': 'Cyclist',
                'Cyclist': 'Cyclist',
                'pedestrian': 'Pedestrian',
                'Pedestrian': 'Pedestrian'}

**Comment by darrenjkt** [comment]
This is because the custom dataset expects class names to be ['Vehicle', 'Pedestrian', 'Cyclist']. The labels you've given it from kitti raw are car, truck, pedestrian etc hence why it's throwing an error. I suggest either changing the CLASS_NAMES/CLASS_MAPPING to keep your kitti labels unchanged or modify your kitti labels to be the same as ['Vehicle', 'Pedestrian', 'Cyclist'].

**Comment by enesdorukadastec** [comment]
thanks for reply @darrenjkt, I adjust class mapping in terms of kitti but I got error again, 

![image](https://github.com/darrenjkt/MS3D/assets/122875953/d2b6f5ec-67b5-447d-bf6a-13cc07a1ef90)

![image](https://github.com/darrenjkt/MS3D/assets/122875953/294243cf-f9d5-4236-999c-bdf829c375b3)

should I comment this section?
