### ISSUE TITLE
Performance effect of pseudo labels on dataset

### ISSUE THREAD

**Issue by enesdorukadastec** [darrenjkt/MS3D#17]
Hi @darrenjkt, 
I am curious that auto label generate FP and FN labels even if we do optimize hyperparameters in terms of our dataset. Did you make an experiment about the usage of auto-label ratio according to the dataset? For instance; my dataset annotation size is 500K. I created 800K  pseudo labels using the auto label tool. Does it make sense? Or did you experience like this study?

**Comment by darrenjkt** [comment]
My understanding of your statement is that you have 500k human-annotated frames and 800k auto-labelled frames right?

I did not do experiments for of combining both human and automatic labels in training a dataset since this work is in unsupervised domain adaptation which assumes you have no labelled data to begin with. 

My intuition is that including more pseudo-labelled data with human-labelled data can give further variation in training samples which leads to model improvement. However auto-labelling errors may also confuse the learning of the model which may affect performance. You'll have to experiment and see what works.

**Comment by enesdorukadastec** [comment]
> My understanding of your statement is that you have 500k human-annotated frames and 800k auto-labelled frames right?
> 
> I did not do experiments for of combining both human and automatic labels in training a dataset since this work is in unsupervised domain adaptation which assumes you have no labelled data to begin with.
> 
> My intuition is that including more pseudo-labelled data with human-labelled data can give further variation in training samples which leads to better model generalisation. However auto-labelling errors may also confuse the learning of the model which may affect performance. You'll have to experiment and see what works.

Yes, it is right. I think the most important thing is that raw data should not include hard instances because of poor accuracy. Thanks  for reply.

**Comment by darrenjkt** [comment]
Sorry I don't understand your question. What do you mean by "like dataset"? Also I don't understand what you mean by "using training auto label" and "using as a dataset". Could you clarify?

**Comment by enesdorukadastec** [comment]
> Sorry I don't understand your question. What do you mean by "like dataset"? Also I don't understand what you mean by "using training auto label" and "using as a dataset". Could you clarify?

Sure, What is the difference between labeling raw data with an auto-label tool to embed dataset, and using without embed dataset? For these two scenarios, we label with the auto-label tool.

**Comment by darrenjkt** [comment]
I think what you're asking is - what's the difference between these two scenarios:
1. Training a model on auto-labelled raw data + human-labelled data (e.g. nuscenes)
2. Training a model only on auto-labelled raw data. 

Mixing auto labelled data and human labelled data for a dataset collected from the same deployment domain can work quite well. 

However, training a model on a mix of your auto-labelled raw data with human-labelled nuscenes data may not help your model performance if your raw data's lidar and data collection environment is very different to nuscenes. If this is the case, you're better off just training with the auto-labelled dataset. 

I hope that I've answered your question
