### ISSUE TITLE
evaluating the fused detections results

### ISSUE THREAD

**Issue by gorkemguzeler** [darrenjkt/MS3D#20]
Hi,

I generated the initial_ps pickle which contains the fused detection results. Now i would like to evaluate the results by comparing to GT using the kitti_eval.get_official_eval_result function. I am pseudo-labeling the kitti dataset that's why my GT is already compatible with the evaluation function. But i am getting several error due to my detection pickle (since original code only keeps the gt_boxes as a key). Is there any easy way to evaluate fused result or should I arrange my detection pickle based on the kitti format? 

Thanks in advance! 

Best regards,

**Comment by darrenjkt** [comment]
I have a python script that evaluates the det pickle in my dev branch. The conversion between the det pkl and kitti det_annos format is pretty straight forward. 

https://github.com/darrenjkt/MS3D/blob/3cdcddd95fc10335b8be9fbe1ee38c7ef761d765/tools/exp_eval_pseudo_labels.py#L64-L78

**Comment by gorkemguzeler** [comment]
Hi @darrenjkt, thanks a lot for your answer. 

I tried using your script with modifications (such as using kitti_eval.get_official_eval_result), however I am confused at some point: 
- location (dim = 3), dimensions (dim = 3), rotation_y (dim=1) keys are used for evaluation in original kitti eval pipeline. 
- we are fusing the lidar_boxes (dim = 7), label (dim=1), score (dim=1) from all detectors in our gt_boxes dict. 
- So, i was thinking whether the lidar_boxes represents the concatenation of [location,dimension,rotation], do you have any idea on this? If that's not the case, how am i supposed to create the fusion of these keys and use kitti eval pipeline?

Best regards,

**Comment by darrenjkt** [comment]
Yes that's correct. The lidar_boxes you get from ps_dict are a (N, 9) np array for N detections. The 9 dimensions refer to (x,y,z,dx,dy,dz,heading,class_id,score) where dx, dy, dz is the box dim in x,y,z axis i.e. length, width, height. 

As to why you're getting zeros in evaluation, this is probably the reason. All the ps_dict stores boxes in the ground frame where the point (0,0,0) is right below the lidar, on the ground level. This is how waymo does it. KITTI and nuscenes define (0,0,0) as the lidar position itself i.e. the lidar frame. Make sure that you've mapped the ps_dict to the KITTI lidar frame by setting "dataset.dataset_cfg.SHIFT_COOR" in that snippet above. For KITTI, this value should be SHIFT_COOR: [0.0, 0.0, 1.6]. 

Try visualizing both the detections ps_dict and KITTI gt in 3D after transforming both to the same frame as a sanity check if they are overlapping. If they are then the evaluation should work.

**Comment by gorkemguzeler** [comment]
Hi @darrenjkt, thanks a lot for your answer.

I visualized the 3D detections with KITTI GT dataset and see that my preds are fine. As you pointed out, I am using dataset.dataset_cfg.SHIFT_COOR to shift the coordinate system and it is crucial for meaningful results. 

I also find out that, my pred dict is generating results corresponding to 'gt_boxes_lidar' key of original KITTI GT which additionaly contains [loc,dim,heading] keys for image. So, I though that was the confusion and replaced these [loc,dim,heading] keys with the values of 'gt_boxes_lidar'. 

However, I still get 0 at my evaluation results (I checked out some of the overlap results which contain some values more than 0.5 - so it should be finding some overlaps). [MS3D/pcdet/datasets/kitti/kitti_object_eval_python/eval.py](https://github.com/darrenjkt/MS3D/blob/main/pcdet/datasets/kitti/kitti_object_eval_python/eval.py#L9)
in the above file, there is the following function at line 122: 
```
def d3_box_overlap_kernel(boxes, qboxes, rinc, criterion=-1):
    # ONLY support overlap in CAMERA, not lider.
```

Is it possible that KITTI does not provide lidar 3D box evaluation or this function is relevant to my issue? 

Best regards,

**Comment by darrenjkt** [comment]
You don't need to format the pred dict into the KITTI format yourself. OpenPCDet defines a unified representation of 3D bboxes. All KITTI, Waymo, nuScenes ground truths are converted into the (x,y,z,dx,dy,dz,heading,class_id,score) format when you prepare the infos as per their dataset preparation page. Your prediction dict should also be in that format. 

All the conversion from your pred dict to the original KITTI format is done in the `kitti_eval.get_official_eval_result` function before evaluating. If you're interested in how they evaluate the KITTI dataset, you can step through that function. 

https://github.com/darrenjkt/MS3D/blob/7e65e6d59d4c9cbc6675dd6fdf155bc2cb53baf8/pcdet/datasets/kitti/kitti_dataset.py#L615-L617

**Comment by gorkemguzeler** [comment]
Hi, 

Thanks for the important information. I think 'gt_boxes_lidar' key of kitti info pickle is the OpenPCDet format while location,dimension,rotation keys are representing the kitti camera frame format.

So given that our predictions are in the same format with OpenPCDet, then using the 'gt_boxes_lidar' is the correct approach, right?

Because when you give `eval_gt_annos = [copy.deepcopy(info['annos']) for info in self.infos] ` this contains the location,dimension keys based on kitti camera and gt_boxes_lidar key which contains the OpenPCDet format. 

Therefore I felt like I need to adjust the GT keys, otherwise I also think that this does not make sense... Maybe the kitti info pickle file I have is different than yours?

**Comment by gorkemguzeler** [comment]
Hi,     
for anyone who goes through a similar problem, using the following function to convert my predictions into KITTI format was necessary:
`
pred_annos= transform_annotations_to_kitti_format(pred_annos,SUPER_MAPPING)
`
before this line: 
` ap_result_str, ap_dict = kitti_eval.get_official_eval_result(eval_gt_annos, eval_det_annos, class_names) `

So, @darrenjkt I do not think kitti_eval.get_official_eval_result does the conversion automatically for your information.

Best,

**Comment by darrenjkt** [comment]
Ah yes, sorry that's my bad. Thanks for updating with the solution. 

To add on to this, you can also see examples in nuscenes and waymo dataset when they use the KITTI eval. They have to transform both their pred and gt annos to kitti format before evaluating with kitti_eval. For example, this is nuscenes conversion for using kitti eval format. 
https://github.com/darrenjkt/MS3D/blob/7e65e6d59d4c9cbc6675dd6fdf155bc2cb53baf8/pcdet/datasets/nuscenes/nuscenes_dataset.py#L245-L305
