### ISSUE TITLE
KITTI ground truth labels provide poor quality

### ISSUE THREAD

**Issue by gorkemguzeler** [darrenjkt/MS3D#26]
Hi @darrenjkt,

Hope you are doing fine! 

I have been using several detectors (pv_rcnn_plusplus and voxel_rcnn models trained on waymo,nuscenes and lyft) in order to label KITTI frames. Then, I noticed that, there are several frames that has missing ground truth boxes even though our detectors were able to label them correctly which made me curious if there is something I am doing wrong or KITTI ground truth is really bad? 

Kind regards,
Gorkem

![Screen Shot 2024-05-05 at 13 08 58](https://github.com/darrenjkt/MS3D/assets/63750570/79060f27-633c-48e6-a974-41fcbbe2fff7)

**Comment by darrenjkt** [comment]
Yeah that's correct. From memory, KITTI ground truth labels do not label objects that are smaller than 25 pixel height. This tends to exclude far range objects that lidar can pick up which is why kitti lidar ground truth is missing labels.

Waymo and nuScenes on the other hand, will label any objects with at least one lidar point in them regardless of image pixel size.

**Comment by gorkemguzeler** [comment]
Hi @darrenjkt, thanks a lot for your reply! 

Then, for the quantitative evaluation purposes; is it a good approach to discard these object somehow? Because this results in a lot of false positives which significantly affects the results. 

Exactly, using the waymo dataset I was able to get reasonable results both quantitative and qualitative... 

Best,

**Comment by darrenjkt** [comment]
Not sure if the openpcdet kitti evaluation already does some filtering but you could dig into their code first. 

If not, you could filter the predictions based on their 3d bounding box pixel height after projecting into the image frame. 

Make sure you re-run this modified evaluation on other algorithms for fair comparison.

**Comment by gorkemguzeler** [comment]
Alright, thanks for your help!
