### ISSUE TITLE
How to change annotation results? 

### ISSUE THREAD

**Issue by zehranrgi** [darrenjkt/MS3D#29]
Hi,

I have 3 questions:

1. Is there a way to change the final labeling results? For example, if we recognize a mistake in labeling, can we correct it?
2. I need to label LiDAR data for trajectory prediction. Can I use this labeling method for this type of problem?
3. For evaluating results, do I need to compare the camera data and LiDAR labeled data one by one? Or do I need to create ground truth labels for them with other applications first?

thank you. 

(I didn't close the other issue, I will reply by showing the error that I got. )

**Comment by darrenjkt** [comment]
Hi, sorry for the late reply

1. No, that would require a separate program more suited for labelling such as CVAT. However this could be the initial starting labels. 
2. This repo is a 3d object detection auto-labelling work I.e. 3d bounding box auto-labelling, which is fundamentally different from trajectory prediction labels. 
3. You could compare the camera data, that would definitely help to visually validate the labels. I don't have that code implemented but it's not too hard to do. If you're just testing ms3d with waymo or nuscenes, they already have gt labels for you to compare against.

**Comment by zehranrgi** [comment]
Thank you for your response.
