### ISSUE TITLE
Question about using MS3D with Multi-Lidar Setup

### ISSUE THREAD

**Issue by melihyazgan** [darrenjkt/MS3D#30]
Hi @darrenjkt,

Thank you for your great effort in open-sourcing such a tool!

I have a setup with multiple lidars mounted in different locations on the car, and I’m working with rosbags from this setup. Based on the MS3D pipeline and the focus on single-lidar sequences, I wanted to get your intuition on the following:

- Do you think it’s better to fuse the point clouds from all lidars first and then create sequences for MS3D to process? OR
- Would it be more effective to create a separate dataset for each lidar and run MS3D labeling on them individually?

Best Regards,
Melih

**Comment by darrenjkt** [comment]
Might be good to try a small test dataset to see how well the pretrained detectors with ms3d work on a fused point cloud. You do get a more holistic view but the scan pattern also becomes drastically different. 

Compare above with running ms3d on individual lidars. You can fuse the boxes from diff lidars with KBF for the final set of labels.
