### ISSUE TITLE
Question about distributed testing

### ISSUE THREAD

**Issue by LiuStan99** [darrenjkt/MS3D#31]
Hi @darrenjkt !

Thanks a lot for your work! 

When I was inferencing using only 1 GPU, I found the CPU load very high and the speed was quite slow. Specifically, all 32 CPU cores were almost used for almost 100%. I found that suspicious since I only set the number of workers as 4 as default. I have tried multiple numbers for batch sizes ranging from 6 to 18, but it did not change the CPU usage much.

But when I tried to infer on 2 GPUs using the [distributed testing script from OpenPCDet](https://github.com/open-mmlab/OpenPCDet/blob/master/tools/scripts/dist_test.sh), the CPU load was much lower, even though the number of workers and batch size were the same as in the previous setting with only 1 GPU. The speed was increased almost 4 times since the CPU was no longer the bottleneck. 

However, I do notice that despite this project being built upon OpenPCDet, the distributed testing script was removed. Does this mean that the original distributed inference script from OpenPCDet should not be used and that I was actually missing something during the distributed inference?  And do you have any insights on the wired CPU behavior?

Thanks you very much in advance!

**Comment by darrenjkt** [comment]
I'm not too sure why the CPU load would be so high with only 1 GPU. You could profile the code if you're interested. Would be good to check your gpu usage and see if the code is actually using your GPU or using CPU to do the model inference. 

 The test.py in this repo was adapted from ST3D but it should work fine with that testing script from openpcdet.

I removed the testing script probably since I wasn't using it

**Comment by LiuStan99** [comment]
Thanks for the reply! 

I think I can use the distributed training script safely in this case. I ran the command in the following script:
```
#!/usr/bin/env bash

set -x
NGPUS=2

python3 -m torch.distributed.launch --nproc_per_node=${NGPUS} test.py --launcher pytorch \
                --cfg_file ../model_zoo/lyft_pretrained/cfgs/uda_voxel_rcnn_anchorhead.yaml \
                --ckpt ../model_zoo/lyft_pretrained/lyft_uda_voxel_rcnn_anchorhead_3xyzt_allcls.pth \
                --eval_tag lyft3xyzt_custom3xyzt_notta \
                --target_dataset custom --sweeps 3 --batch_size 16 --use_tta 0 \
                --set DATA_CONFIG_TAR.DATA_SPLIT.test train MODEL.POST_PROCESSING.EVAL_METRIC none  
```

 Regarding the CPU load, the high load peak happens when the batch is being transported to GPU in the function `load_data_to_gpu`. I guess it may be because the tensors are quite large in my case.
