### ISSUE TITLE
Question about weighting the detetction boxes for ensemble

### ISSUE THREAD

**Issue by LiuStan99** [darrenjkt/MS3D#32]
Hi @darrenjkt ,

Thanks a lot for the continuous support! 

When ensembling detection boxes from different results, it seems that we can manually assign different weights for different results by padding the values behind the detection path in the [text file](https://github.com/darrenjkt/MS3D/blob/main/tools/cfgs/target_custom/label_generation/round1/cfgs/ensemble_detections.txt).

However, when I look at the code, it seems that the values given should be [integers only](https://github.com/darrenjkt/MS3D/blob/ffed761a6846183966cc38d3144c90d91446fa4a/pcdet/utils/box_fusion_utils.py#L147), or at least they will be converted as integers. So does this mean we should assign a higher integer (say 100) if we trust one result more? Or can I change the code so that the box weights can be accepted as floats and just limit the weight range from 0 to 1?

Thanks in advance. Any insights from you would be helpful and appreciated!

**Comment by darrenjkt** [comment]
Sorry for the late reply. You don't have to use integers. Floats are fine. I'm not sure how much difference you would see if you had e.g. 1 vs 1.5  compared to 1 vs 2 though. Give it a shot and see how it is. 

The weight is a heuristic that needs a bit of tuning based on your knowledge of how the pretrained detectors perform.

**Comment by LiuStan99** [comment]
Thanks a lot for the valuable insights! I will give it a try.
