### ISSUE TITLE
the raw data of kitti dataset

### ISSUE THREAD

**Issue by OuyangJunyuan** [darrenjkt/MS3D#5]
Hi, thanks for your awesome research!
I am confused that does the `kitti_raw_dataset` be used in this work? if yes, could you tell me which sequences are included?

**Comment by darrenjkt** [comment]
Thanks for your interest in this work. I have not double-checked the codes for KITTI raw in this code release. The kitti_dataset.py does work in general but you might need to fix some bugs as they pop up. Feel free to try it out and let me know. I do not directly address the sizing issue in KITTI however; you can get good detections with this repo so 0.5 IoU AP should be good, but 0.7 IoU AP may be low.

This repo is not limited to specific kitti raw sequences. There are not many frames in each KITTI raw sequence so you'll have to download a few sequences to have a decent amount of training data. I used [KISS-ICP](https://github.com/PRBonn/kiss-icp) to get the ego-pose for frame-accumulation of each sequence.

**Comment by OuyangJunyuan** [comment]
Thanks for your detailed reply. It's helpful to me.
